import { agents, askAI } from './ai.js';
import { addAudit, consumeRecipe, faNum, loadState, lowStock, money, orderTotal, saveState, todaySales } from './store.js';
let state = loadState();
const routes = ['/login','/dashboard','/pos','/tables','/orders','/menu','/kitchen','/inventory','/purchases','/accounting','/customers','/staff','/reservations','/reports','/ai','/settings','/notifications','/audit'];
const nav = [['/dashboard','داشبورد','📊'],['/pos','POS','🧾'],['/tables','میزها','🪑'],['/orders','سفارش‌ها','🔥'],['/menu','منو','🍽️'],['/kitchen','آشپزخانه','👨‍🍳'],['/inventory','انبار','📦'],['/purchases','خرید','🛒'],['/accounting','حسابداری','💰'],['/customers','مشتریان','💎'],['/staff','کارکنان','👥'],['/reservations','رزرو','📅'],['/reports','گزارشات','📈'],['/ai','AI Manager','🤖'],['/settings','تنظیمات','⚙️'],['/notifications','اعلان‌ها','🔔'],['/audit','Audit','🛡️']];
const $ = (s) => document.querySelector(s); const uid=()=>crypto.randomUUID(); const persist=()=>saveState(state);
function go(path){ history.pushState({},'',path); render(); }
window.addEventListener('popstate', render); window.addEventListener('online',()=>toast('اتصال برقرار شد')); window.addEventListener('offline',()=>toast('حالت آفلاین فعال شد'));
function layout(content){ const path=location.pathname; if(path==='/login') return login(); return `<aside class="side"><div class="brand"><b>Molazhi</b><span>ERP AI</span></div>${nav.map(n=>`<button class="nav ${path===n[0]?'active':''}" data-go="${n[0]}">${n[2]} ${n[1]}</button>`).join('')}<button id="logout" class="nav danger">خروج</button></aside><main class="main"><div class="top"><div><h1>${nav.find(n=>n[0]===path)?.[1]||'داشبورد'}</h1><p>${navigator.onLine?'آنلاین':'آفلاین'} • نقش‌ها: ${state.session?.roles?.join('، ')}</p></div><button id="install" class="btn primary">Install App</button></div><div id="toast"></div><div class="offline ${navigator.onLine?'hide':''}">شما آفلاین هستید؛ فقط UI و سفارش‌های موقت غیرحساس کش می‌شوند.</div>${content}</main>`; }
function login(){ return `<main class="login"><section class="login-card"><h1>ورود به Molazhi ERP AI</h1><p>سامانه جامع مدیریت رستوران و کافه</p><form id="loginForm"><input id="phone" value="09120000000" placeholder="شماره موبایل"><input id="pin" value="1234" placeholder="PIN" type="password"><button class="btn primary">ورود امن</button></form><small>کاربر نمونه: 09120000000 / 1234</small></section></main>`; }
function dashboard(){ const sales=todaySales(state), count=state.orders.length, avg=sales/(count||1), profit=sales*.48, expense=sales*.22; return `<section class="kpis">${[['فروش امروز',sales],['تعداد سفارش',count],['میانگین فاکتور',avg],['سود',profit],['هزینه',expense],['میزهای فعال',state.tables.filter(t=>t.status==='busy').length],['سفارش آشپزخانه',state.orders.filter(o=>['SENT_TO_KITCHEN','PREPARING'].includes(o.status)).length],['کم‌موجودی',lowStock(state).length]].map(([a,b])=>`<article class="card"><span>${a}</span><b>${typeof b==='number'&&b>1000?money(b):faNum(b)}</b></article>`).join('')}</section><section class="grid two"><div class="panel"><h2>فروش، سود، هزینه، سفارش</h2><canvas id="salesChart"></canvas></div><div class="panel"><h2>محصولات پرفروش</h2><canvas id="topChart"></canvas></div></section>`; }
function pos(){ return `<section class="pos"><div class="panel"><h2>محصولات</h2><input id="search" class="search" placeholder="جستجوی محصول"><div class="chips">${state.categories.map(c=>`<button data-cat="${c.id}">${c.name}</button>`).join('')}</div><div id="products" class="products"></div></div><div class="panel bill"><h2>فاکتور</h2><select id="tablePick">${state.tables.map(t=>`<option value="${t.id}">${t.title} - ${t.status}</option>`)}</select><select id="customerPick"><option value="">مشتری مهمان</option>${state.customers.map(c=>`<option value="${c.id}">${c.name}</option>`)}</select><div id="cart"></div><input id="note" placeholder="یادداشت سفارش / Modifier"><div class="actions"><button id="payCash" class="btn primary">پرداخت نقدی</button><button id="payCard" class="btn">کارت</button><button id="split" class="btn">Split Bill</button><button id="refund" class="btn danger">Refund</button></div></div></section>`; }
function tablePage(){ return `<section class="table-grid">${state.tables.map(t=>`<article class="table ${t.status}"><h3>${t.title}</h3><p>${t.floor} • ${t.seats} نفره</p><b>${statusFa(t.status)}</b><div><button data-table="${t.id}" data-status="busy">بازکردن</button><button data-table="${t.id}" data-status="reserved">رزرو</button><button data-table="${t.id}" data-status="free">بستن</button></div></article>`).join('')}</section>`; }
function ordersPage(){ return `<div class="panel"><h2>چرخه وضعیت سفارش</h2><p>DRAFT → CONFIRMED → SENT_TO_KITCHEN → PREPARING → READY → SERVED → PAID → CLOSED / CANCELLED / REFUNDED</p></div><section class="list">${state.orders.map(o=>`<article class="row"><div><b>${o.id}</b><span>${o.type} • ${state.tables.find(t=>t.id===o.tableId)?.title||'بدون میز'} • ${money(orderTotal(state,o))}</span></div><select data-order-status="${o.id}">${['DRAFT','CONFIRMED','SENT_TO_KITCHEN','PREPARING','READY','SERVED','PAID','CLOSED','CANCELLED','REFUNDED'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`)}</select></article>`).join('')}</section>`; }
function menuPage(){ return crud('منو و Recipe', state.products, p=>`${p.image} ${p.name}`, p=>`${p.sku} • ${money(p.price)} • مالیات ${p.tax}% • Station ${p.station} • Recipe: ${p.recipe?.map(r=>r.join(' ')).join(', ')}`); }
function inventoryPage(){ return crud('انبار و Movement', state.inventory, i=>i.name, i=>`${faNum(i.stock)} ${i.unit} • حداقل ${faNum(i.min)} • ${i.supplier} • انقضا ${i.expiry}`); }
function purchases(){ return crud('تأمین‌کنندگان و سفارش خرید', state.suppliers, s=>s.name, s=>`بدهی: ${money(s.debt)} • دریافت کالا، مرجوعی و قیمت خرید آماده ثبت است.`); }
function accounting(){ const s=todaySales(state); return `<section class="kpis">${[['فروش',s],['هزینه',s*.22],['درآمد',s],['بهای تمام‌شده',s*.30],['سود ناخالص',s*.48],['سود خالص',s*.36],['جریان نقدی',state.cash.actual]].map(([a,b])=>`<article class="card"><span>${a}</span><b>${money(b)}</b></article>`).join('')}</section><div class="panel"><h2>صندوق</h2><p>موجودی اولیه ${money(state.cash.opening)} • دریافت ${money(state.cash.receipts)} • پرداخت ${money(state.cash.payouts)} • Refund ${money(state.cash.refunds)} • اختلاف ${money(state.cash.actual-state.cash.expected)}</p></div>`; }
function customers(){ return crud('CRM و Loyalty', state.customers, c=>c.name, c=>`${c.phone} • خرید کل ${money(c.total)} • امتیاز ${faNum(c.points)} • کیف پول ${money(c.wallet)} • ${c.address}`); }
function staffPage(){ return crud('کارکنان، شیفت، حضور، حقوق', state.staff, e=>e.name, e=>`${e.role} • شیفت ${e.shift} • ${e.attendance} • حقوق ${money(e.salary)} • عملکرد ${faNum(e.performance)}٪`); }
function reservationsPage(){ return crud('رزروها', state.reservations, r=>r.customer, r=>`${r.date} ساعت ${r.time} • ${r.guests} نفر • ${r.table} • ${r.status} • ${r.note}`); }
function reports(){ return `<div class="panel"><h2>گزارشات</h2><div class="chips">${['امروز','هفته','ماه','سال','بازه دلخواه'].map(x=>`<button>${x}</button>`).join('')}</div><div class="report-grid">${['فروش','سود','هزینه','محصول','دسته‌بندی','انبار','ضایعات','خرید','مشتری','کارکنان','صندوق'].map(x=>`<article class="card"><span>${x}</span><b>${money(Math.random()*10000000+1000000)}</b></article>`).join('')}</div></div>`; }
function aiPage(){ return `<section class="panel ai"><h2>🤖 AI Manager</h2><p>Agents: ${agents.join(' • ')}</p><textarea id="aiQ" placeholder="سؤال خود را بنویسید... مثلا فروش امروز چقدر است؟"></textarea><button id="ask" class="btn primary">تحلیل کن</button><div id="aiA" class="answer">AI فقط با داده کافی پیش‌بینی می‌کند و عملیات حساس را بدون تأیید انجام نمی‌دهد.</div></section>`; }
function settings(){ return `<div class="panel"><h2>تنظیمات سیستم</h2><p>امتیاز وفاداری: هر ${money(state.settings.loyaltyRate.amount)} خرید = ${faNum(state.settings.loyaltyRate.points)} امتیاز</p><p>مالیات پیش‌فرض: ${state.settings.taxDefault}% • Safe Mode AI: فعال</p><p>Entityهای دیتابیس: ${state.entities.join('، ')}</p></div>`; }
function notifications(){ return crud('اعلان‌ها', state.notifications, n=>n.title, n=>n.body); }
function audit(){ return crud('Audit Logs', state.auditLogs, a=>a.action, a=>`${a.actor} • ${a.target} • ${a.time}`); }
function kitchen(){ return `<section class="kanban">${['SENT_TO_KITCHEN','PREPARING','READY','DELAY'].map(col=>`<div class="panel"><h2>${col}</h2>${state.orders.filter(o=>col==='DELAY'?Date.now()-o.createdAt>30*60000:o.status===col).map(o=>`<article class="ticket"><b>${o.id}</b><span>${Math.round((Date.now()-o.createdAt)/60000)} دقیقه • ${o.items.map(i=>state.products.find(p=>p.id===i.productId)?.name).join('، ')}</span><button data-kitchen="${o.id}">مرحله بعد</button></article>`).join('')||'<p class="empty">موردی نیست</p>'}</div>`).join('')}</section>`; }
function crud(title, arr, head, body){ return `<div class="panel"><div class="toolbar"><h2>${title}</h2><input class="search" placeholder="جستجو"><button class="btn primary">افزودن</button></div><section class="list">${arr.map(x=>`<article class="row"><div><b>${head(x)}</b><span>${body(x)}</span></div><button class="btn">ویرایش</button></article>`).join('')||'<p class="empty">داده‌ای وجود ندارد</p>'}</section></div>`; }
function statusFa(s){ return ({free:'آزاد',busy:'مشغول',reserved:'رزرو',cleaning:'در حال نظافت',out:'خارج از سرویس'})[s]||s; }
function render(){ let path=routes.includes(location.pathname)?location.pathname:'/dashboard'; if(!state.session) path='/login'; const map={'/dashboard':dashboard,'/pos':pos,'/tables':tablePage,'/orders':ordersPage,'/menu':menuPage,'/kitchen':kitchen,'/inventory':inventoryPage,'/purchases':purchases,'/accounting':accounting,'/customers':customers,'/staff':staffPage,'/reservations':reservationsPage,'/reports':reports,'/ai':aiPage,'/settings':settings,'/notifications':notifications,'/audit':audit}; $('#app').innerHTML=layout(path==='/login'?'':map[path]()); bind(); drawCharts(); }
function bind(){ document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go)); $('#logout')?.addEventListener('click',()=>{addAudit(state,'Logout','سیستم'); state.session=null; persist(); go('/login');}); $('#loginForm')?.addEventListener('submit',e=>{e.preventDefault(); const u=state.users.find(x=>x.phone===$('#phone').value&&x.pin===$('#pin').value); if(u){state.session={id:u.id,name:u.name,roles:u.roles}; addAudit(state,'Login','سیستم'); persist(); go('/dashboard');} else toast('اطلاعات ورود نادرست است');}); document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{const t=state.tables.find(x=>x.id===b.dataset.table); t.status=b.dataset.status; addAudit(state,'Update',t.title); persist(); render();}); document.querySelectorAll('[data-order-status]').forEach(s=>s.onchange=()=>{const o=state.orders.find(x=>x.id===s.dataset.orderStatus); o.status=s.value; state.orderStatusHistory.unshift({id:uid(),orderId:o.id,status:o.status,time:new Date().toISOString()}); if(o.status==='PAID') consumeRecipe(state,o); addAudit(state,'Update',o.id); persist(); render();}); $('#ask')?.addEventListener('click',()=>{$('#aiA').textContent=askAI(state,$('#aiQ').value);}); if(location.pathname==='/pos') bindPOS(); }
function bindPOS(){ let cart=[]; const renderProducts=()=>{$('#products').innerHTML=state.products.map(p=>`<button class="product" data-p="${p.id}"><span>${p.image}</span><b>${p.name}</b><small>${money(p.price)}</small></button>`).join(''); document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{cart.push({productId:b.dataset.p,qty:1}); renderCart();});}; const renderCart=()=>{$('#cart').innerHTML=cart.map((i,idx)=>{const p=state.products.find(x=>x.id===i.productId);return `<div class="cart"><span>${p.name}</span><b>${money(p.price*i.qty)}</b><button data-del="${idx}">×</button></div>`}).join('')+`<h3>جمع: ${money(cart.reduce((s,i)=>s+(state.products.find(p=>p.id===i.productId)?.price||0)*i.qty,0))}</h3>`; document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.del,1);renderCart();});}; const pay=(method)=>{ if(!cart.length) return toast('سبد خالی است'); const order={id:`o${Date.now()}`,tableId:$('#tablePick').value,customerId:$('#customerPick').value,type:'DINE_IN',status:'PAID',createdAt:Date.now(),items:cart,discount:0,payments:[{method,amount:0}]}; state.orders.unshift(order); consumeRecipe(state,order); addAudit(state,'Create',order.id); persist(); toast('سفارش ثبت و رسید آماده چاپ شد'); cart=[]; renderCart();}; renderProducts(); renderCart(); $('#payCash').onclick=()=>pay('CASH'); $('#payCard').onclick=()=>pay('CARD'); $('#split').onclick=()=>toast('Split Bill فعال است؛ پرداخت چندگانه در فاکتور ذخیره می‌شود.'); $('#refund').onclick=()=>confirm('Refund عملیات حساس است. تأیید می‌کنید؟')&&toast('درخواست Refund به صف تأیید مدیر ارسال شد.'); }
function drawCharts(){ if(!window.Chart || location.pathname!=='/dashboard') return; new Chart($('#salesChart'),{type:'line',data:{labels:['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه'],datasets:[{label:'فروش',data:[12,19,16,24,21,28],borderColor:'#E50914'},{label:'سود',data:[5,8,7,11,10,13],borderColor:'#22c55e'},{label:'هزینه',data:[3,4,5,6,5,7],borderColor:'#f59e0b'}]}}); new Chart($('#topChart'),{type:'doughnut',data:{labels:state.products.map(p=>p.name),datasets:[{data:state.products.map((_,i)=>[12,10,8,6,5][i]||3),backgroundColor:['#E50914','#991b1b','#f97316','#22c55e','#38bdf8']}]}}); }
function toast(msg){ const t=$('#toast')||document.body.appendChild(document.createElement('div')); t.id='toast'; t.textContent=msg; t.className='show'; setTimeout(()=>t.className='',2600); }
let deferred; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault(); deferred=e;}); document.addEventListener('click',e=>{ if(e.target.id==='install'&&deferred) deferred.prompt(); });
if('serviceWorker' in navigator) navigator.serviceWorker.register('/service-worker.js');
render();
